// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qrpvmlifioraboogwwfe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFycHZtbGlmaW9yYWJvb2d3d2ZlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkxNzQxMDUsImV4cCI6MjA3NDc1MDEwNX0.dQbHKI7FA0Qrb8R9ezagTAAi8OHWnE_urvS7NXEfubQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});